### ISSUE TITLE
$http undefined

### ISSUE THREAD

**Issue by borag** [cerebral/cerebral-angular#7]
Why do I get Uncaught TypeError: Cannot set property '$http' of undefined

**Comment by christianalfoni** [comment]
In what situation does this happen? And with what version?

**Comment by pltnkv** [comment]
I got this error too. Just follow instructions:
npm install
npm start
open http://localhost:8080/

Uncaught TypeError: Cannot set property '$http' of undefined
`(anonymous function) @ index.js:40angular.module.provider.$get @ index.js:39invoke @ angular.js:4523(anonymous function) @ angular.js:4340getService @ angular.js:4482invoke @ angular.js:4514(anonymous function) @ angular.js:4344forEach @ angular.js:340createInjector @ angular.js:4344doBootstrap @ angular.js:1676bootstrap @ angular.js:1697angularInit @ angular.js:1591(anonymous function) @ angular.js:29013trigger @ angular.js:3057defaultHandlerWrapper @ angular.js:3346eventHandler @ angular.js:3334
`

**Comment by christianalfoni** [comment]
Hi guys!

`cerebral-angular` has been a bit neglected as the project has been moving forward. It is working, it is just the demo app that was not updated to work with the latest version.

It would be really great with some help on this. For example using the boilerplate here: https://github.com/cerebral/cerebral-boilerplate and replace react with Angular :-)

**Comment by pltnkv** [comment]
I fixed *cerebral-angular* app. But use baobab-js (with baobab monkeys) instead immutable-js because of cerebral-immutable-* is deprecated.
https://github.com/pltnkv/cerebral-angular

I can make pull request if need.

**Comment by christianalfoni** [comment]
That is awesome @pltnkv! Please create a pull request on it :-)
